feat(output): print out the filename of the test case
Kong/busted-hjtest pull request #1
Opened 2023-07-24 08:02 UTC by AndyZhang0707

Print out the filename of the test case which is useful to analyze test results based on the test files.

2023-07-24 08:02 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/signed)](https://cla-assistant.io/Kong/busted-hjtest?pullRequest=1) <br/>All committers have signed the CLA.

2023-07-25 01:38 UTC, ADD-SP requested changes
Could you please bump the `.rockspec` file?

2023-07-25 01:58 UTC, ADD-SP approved these changes

2023-07-25 01:58 UTC, AndyZhang0707 commented
> Could you please bump the `.rockspec` file?

Done

2023-07-25 01:59 UTC, merged